### ISSUE TITLE
Error using parallel symbolic factorization with v9.0.0

### ISSUE THREAD

**Issue by sebastiangrimberg** [xiaoyeli/superlu_dist#161]
The routines in [`psymbfact.c`](https://github.com/xiaoyeli/superlu_dist/blob/master/SRC/prec-independent/psymbfact.c) call [`psymbfact_LUXpandMem`](https://github.com/xiaoyeli/superlu_dist/blob/master/SRC/prec-independent/psymbfact_util.c#L91) with `mem_type` set to 0 or 1. However, after [this commit](https://github.com/xiaoyeli/superlu_dist/commit/e2076918152efa9a6d44bf87e4c7fef9efd6d5d2#diff-4964d63c55baaf45c54e2d8b0485e230848b1a9da1d7c9fa40bdc3f77442c08d), these no longer relate to `USUB` and `LSUB` which is what `psymbfact_LUXpandMem` expects, leading to the following failure:

```
ABORT("Tries to expand nonexisting memory type.\n");
```

I noticed this when trying to use ParMETIS for the symbolic factorization with the new release of `master`, and only for certain processor counts.

**Comment by xiaoyeli** [comment]
Thanks for reporting this. I just pushed the fix in master branch, among other fixes. Please give a try.

**Comment by sebastiangrimberg** [comment]
Actually, this didn't fully fix the issue. There are a few missed spots still using `computeL`. Here is a patch to fix the remaining:

```
diff --git a/SRC/prec-independent/psymbfact.c b/SRC/prec-independent/psymbfact.c
index ff4b617e..9cbff4e4 100755
--- a/SRC/prec-independent/psymbfact.c
+++ b/SRC/prec-independent/psymbfact.c
@@ -2156,17 +2156,16 @@ symbfact_vtx
 
 	/* TEST available memory */
 	if (next >= x_aind_end) {	
+ 	  int mem_type = (computeL ? LSUB : USUB);  // Sherry fix 5/26/24
 	  if (domain_symb) {
-	      int mem_type = (computeL ? LSUB : USUB);  // Sherry fix 5/26/24 
 	      if ( (mem_error =
 		    psymbfact_LUXpandMem (iam, n, vtx, next, 0,
-					  //computeL, DOMAIN_SYMB, 1, 
 					  mem_type, DOMAIN_SYMB, 1, 
 					  Pslu_freeable, Llu_symbfact, VInfo, PS)) )
 		  return (mem_error);
 	  } else if ( (mem_error =
 		       psymbfact_LUXpand (iam, n, SLU_EMPTY, vtx, &next, 0, 
-					  computeL, LL_SYMB, 1, 
+					  mem_type, LL_SYMB, 1, 
 					  Pslu_freeable, Llu_symbfact, VInfo, PS)) )
 	    return (mem_error);
 
@@ -2340,8 +2339,9 @@ updateRcvd_prGraph
 
   /* test if enough memory in usubPr array */
   if (ind >= szsubPr) {
+      int mem_type = (computeL ? LSUB : USUB);  // Sherry fix 5/26/24
       if ( (mem_error = 
-	    psymbfact_prLUXpand (iam, ind, computeL, Llu_symbfact, PS)) )
+	    psymbfact_prLUXpand (iam, ind, mem_type, Llu_symbfact, PS)) )
 	  return (mem_error);
     if (computeL) 
       subPr = Llu_symbfact->lsubPr;  
@@ -2461,8 +2461,9 @@ update_prGraph
     if (sn_elt < lstVtx_blk) {
       sn_elt_prid = LOCAL_IND( globToLoc[sn_elt] ) - pr_offset;
       if ((*p_indsubPr) + 2 >= szsubPr) {
+ 	  int mem_type = (computeL ? LSUB : USUB);  // Sherry fix 5/26/24
 	  if ( (mem_error = 
-		psymbfact_prLUXpand (iam, 0, computeL, Llu_symbfact, PS)) )
+		psymbfact_prLUXpand (iam, 0, mem_type, Llu_symbfact, PS)) )
 	      return (mem_error);
 	if (computeL) {
 	  subPr = Llu_symbfact->lsubPr;  szsubPr = Llu_symbfact->szLsubPr;
@@ -3317,10 +3318,13 @@ expand_RL
   }
 
   nextl = xlsub[vtxXp_lid+1];  
-  if ( (mem_error = 
-	psymbfact_LUXpand_RL (iam, n, vtxXp, nextl, len_texp, 
-			      computeL, Pslu_freeable, Llu_symbfact, VInfo, PS)) )
-      return (mem_error);
+  {
+    int mem_type = (computeL ? LSUB : USUB);  // Sherry fix 5/26/24
+    if ( (mem_error = 
+  	psymbfact_LUXpand_RL (iam, n, vtxXp, nextl, len_texp, 
+  			      mem_type, Pslu_freeable, Llu_symbfact, VInfo, PS)) )
+        return (mem_error);
+  }
 
   return 0;
 }
@@ -4014,7 +4018,6 @@ dnsCurSep_symbfact
 	      int mem_type = (computeL ? LSUB : USUB);  // Sherry fix 5/26/24 
 	      if ( (mem_error =
 		    psymbfact_LUXpandMem (iam, n, vtx, next, next + j,
-					  //computeL, DNS_CURSEP, 1,
 					  mem_type, DNS_CURSEP, 1,
 					  Pslu_freeable, Llu_symbfact, VInfo, PS)) )
 	      return (mem_error);
```

**Comment by xiaoyeli** [comment]
Thanks! Can you set up a PR ?

**Comment by sebastiangrimberg** [comment]
See #164.
